language: php
php:
  - '7.0'
  - '7.1'
  - nightly
install:
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_script:
  - php ./vendor/bin/coveralls -v
